name: rust_build_test

permissions:
  contents: write

on:
  push:
    branches:
      - "build_test"

jobs:
  tagged-release-test:
    name: "Tagged Release Test"
    runs-on: "ubuntu-latest"
    steps:
      # ...
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Rust Build Test"
          prerelease: true

  upload-assets-test:
    name: "Upload assets"
    needs: tagged-release-test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: "upload rust binary action"
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          ref: refs/tags/latest
          bin: quake
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
